website/quote/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^(?P<quote_id>[0-9]+)/$', views.detail, name='detail')
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from quote import views

router = routers.DefaultRouter()
router.register(r'api/quote', views.QuoteViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^quote/', include('quote.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

website/quote/models.py
from django.db import models


class Quote(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateField('date published')

    def __str__(self):
        return self.title


class Image(models.Model):
    url = models.CharField(max_length=100)
    quote = models.ForeignKey(Quote)

    def __str__(self):
        return self.url

website/quote/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse
from .models import Quote, Image
from .serializers import QuoteSerializer, ImageSerializer
from rest_framework import viewsets

def index(request):
    latest_quotes_list = Quote.objects.order_by('-pub_date')[:]
    context = {'latest_quotes_list': latest_quotes_list}

    return render(request, 'quote/index.html', context)

def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quote/detail.html', {'quote': quote})

def about(request):

    return render(request, 'quote/about.html')

class QuoteViewSet(viewsets.ModelViewSet):
    """
    API endpoint that show all the quotes ordered by date.
    """
    queryset = Quote.objects.all().order_by('-pub_date')
    serializer_class = QuoteSerializer


class ImageViewSet(viewsets.ModelViewSet):
    """
    API endpoint that show the image url.
    """

website/quote/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title> Daily Price </title>
    {% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'todc-bootstrap/css/bootstrap.min.css' %}" />

    <!-- TODC Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'todc-bootstrap/css/todc-bootstrap.min.css' %}" />

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://dailyprice.info/quote/">Daily Price</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="http://dailyprice.info/quote/">Home</a></li>
            <li><a href="http://dailyprice.info/quote/about/">About</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

    <div class="container">
        <div class="row">
        {% block content %}{% endblock %}
    </div>
    </div><!--/.container-->


    <div id="footer">
        <div class="container">
             <p class="text-muted">Daily Price 2015</p>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

website/quote/templates/quote/about.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
            <h1>About Us</h1>
            <p>Our team is made up by 4 greate members.</p>
            <p>Kelger built the website, and wrote a spider to crawl daily price of apple product from appletuan.com.</p>
            <p>Lecision deployed the website using uWSGI and Nginx.</p>
            <p>Liu Y.J made pressure test on the website with a tool named webbench.</p>
            <p>Cuocuo analyzed the result of webbench and carried out load balance to improve the server's performance.</p>
            <p>You can contact us by email: gaigai508@gmail.com.</p>
</div>
{% endblock %}

website/quote/templates/quote/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}{% endblock %} -- 苹果每日报价</title>

    <!-- Bootstrap core CSS -->
    <link href="static/todc-bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- TODC Bootstrap core CSS -->
    <link href="{{ STATIC_ROOT }}todc-bootstrap/css/todc-bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_ROOT  }}css/main.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://dailyprice.info/quote/">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

    <div class="container">
        {% block content %}{% endblock %}
    </div><!--/.container-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

website/quote/templates/quote/detail.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <h1>{{ quote.title }}</h1>
    <p>{{ quote.pub_date }}</p>
</div>

<div class="post">
{% for url in quote.image_set.all %}
<center><img src="{{ url.url }}"><center>
{% endfor %}
</div>
{% endblock %}

website/quote/templates/quote/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
            <h1>Daily Price</h1>
            <p>This website is an example using django and nginx. The function is showing everyday price of apple products.</p>
</div>
{% if latest_quotes_list %}
<div class="post">

<div class="list-group">
    {% for quote in latest_quotes_list %}
        <a href="/quote/{{ quote.id }}/" class="list-group-item">{{ quote.title }}</a>
    {% endfor %}
</div>
{% else %}
    <p>No quotes are available.</p>
</div>
{% endif %}
{% endblock %}